# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
   slack: circleci/slack@4.10.1

jobs:
   build:
      docker:
         - image: circleci/python:3.7.3-stretch
      working_directory: ~/
      steps:
         - checkout
         - run:
            name: Build and push to docker hub
            command: |
               docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
               docker build -t ${DOCKERHUB_USERNAME}/nginx-hello:latest .
               docker push ${DOCKERHUB_USERNAME}/nginx-hello:latest
               docker tag ${DOCKERHUB_USERNAME}/nginx-hello:latest ${DOCKERHUB_USERNAME}/nginx-hello:latest
               docker push ${DOCKERHUB_USERNAME}/nginx-hello:latest

workflows:
   capstone:
      jobs:
         - build
      