# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
   slack: circleci/slack@4.10.1

jobs:
   install:
      docker:
         - image: circleci/python:3.7.3-stretch
      working_directory: ~/repo
      steps:
         - checkout
         - run:
            name: Install dependencies and Lint app
            command: |
               python3 -m venv venv
               . venv/bin/activate
               cd nginx-hello
               make install
               # Install hadolint
               wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
               chmod +x /bin/hadolint
         - run:
            name: run lint
            command: |
               make lint 
         - save_cache:
            paths: [./venv]
            key: venv

   build:
      docker:
         - image: circleci/python:3.7.3-stretch
      working_directory: ~/app
      steps:
         - checkout
         - run:
            name: Build and push to docker hub
            command: |
               cd nginx-hello
               docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
               docker build -t ${DOCKERHUB_USERNAME}/nginx-hello:latest .
               docker push ${DOCKERHUB_USERNAME}/nginx-hello:latest
               docker tag ${DOCKERHUB_USERNAME}/nginx-hello:latest ${DOCKERHUB_USERNAME}/nginx-hello:latest
               docker push ${DOCKERHUB_USERNAME}/nginx-hello:latest

workflows:
   capstone:
      jobs:
         - install
         - build:
            requires: [install]
      
      