# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  slack: circleci/slack@4.10.1

jobs:
   install:
      docker:
         - image: circleci/node:13.8.0
      steps:
         - checkout
         - run: |
            cd nginx-hello
            make install
   build:
      docker:
         - image: circleci/node:13.8.0
      steps:
         - checkout
         - run: |
            cd nginx-hello
            make build
   push:
      docker:
         - image: circleci/node:13.8.0
      steps:
         - checkout
         - run: |
            cd nginx-hello
            make push
   test:
      docker:
         - image: circleci/node:13.8.0
      steps:
         - checkout
         - run: |
            cd nginx-hello
            make test
   

workflows:
  capstone:
    jobs:
      - install
      - build:
            requires: [install]
      - push:
            requires: [build]
      - test:
            requires: [push]
      