# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  slack: circleci/slack@4.10.1

jobs:
   build:
      docker:
         - image: cimg/base:2021.04
         auth:
            username: ${DOCKERHUB_USERNAME}
            password: ${DOCKERHUB_PASSWORD}
      steps:
         - checkout
         - run:
            name: Build docker
            command: |
               cd nginx-hello
               make build
         - run:
            name: Push docker
            command: |
               cd nginx-hello
               make build

workflows:
   capstone:
      jobs:
         - build
      