# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  slack: circleci/slack@4.10.1

jobs:
   build:
      docker:
         - image: python:3.7.3-stretch
      steps:
         - checkout
         - run:
            name: Setup eviroment
            command: |
               python3 -m venv venv
               . venv/bin/activate
               # Install hadolint
               wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
               chmod +x /bin/hadolint
         - run:
            name: Install dependence
            command: |
               cd nginx-hello
               make install
         - run:
            name: Building image
            command: |
               cd nginx-hello
               docker build -t thanhbao0390/nginx-hello:1.0 .
         - save_cache:
            paths: [capstone]
            key: nginx-hello-build
   
   

workflows:
  capstone:
    jobs:
      - build
      