# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  slack: circleci/slack@4.10.1

jobs:
   build:
      docker:
         - image: python:3.7.3-stretch
      steps:
         - checkout
         - run: |
            cd nginx-hello
            make build
   push:
      docker:
         - image: python:3.7.3-stretch
      steps:
         - checkout
         - run: |
            cd nginx-hello
            make push
   test:
      docker:
         - image: python:3.7.3-stretch
      steps:
         - checkout
         - run: |
            cd nginx-hello
            make test
   

workflows:
  capstone:
    jobs:
      - build
      - push:
            requires: [build]
      - test:
            requires: [push]
      